---
sudo: required
language: bash
services: docker

env:
  matrix:
  # missing centos 7 / 8
    - dist: bionic
    - dist: xenial

script:
  - sudo chmod +x ansible_convenience_script.sh
  - sudo ./ansible_convenience_script.sh