---
sudo: required
language: bash
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

script:
  - sudo ./ansible_convenience_script.sh