name: CI
on: [*] #push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["ubuntu:xenial", "ubuntu:bionic", "centos:7", "centos:8"]
    steps:
    - uses: actions/checkout@v1

    - name: Allow execute on script
      run: chmod +x ansible_convenience_script.sh

    - name: run container
      run: "docker run -d -it --name container -v $(pwd):/tmp ${{ matrix.container }}"

    - name: run script in container
      run: docker exec container bash /tmp/ansible_convenience_script.sh