name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["ubuntu:16.04", "ubuntu:18.04", "centos:7", "centos:8"]
    steps:
    - uses: actions/checkout@v1

    - name: Allow execute on script
      run: chmod +x ansible_convenience_script.sh

    - name: run container
      run: "docker run -d -it --name test-container -v $(pwd):/tmp ${{ matrix.container }}"

    - name: run script in container
      run: docker exec test-container /bin/bash -v /tmp/ansible_convenience_script.sh